# Generated by Django 6.0 on 2025-12-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='message',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='service_type',
            new_name='service',
        ),
    ]
