# Generated by Django 6.0 on 2025-12-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_address_alter_booking_preferred_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='address',
            new_name='notenaddress',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='note',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='preferred_time',
        ),
    ]
