# Generated by Django 6.0 on 2025-12-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_address_booking_notenaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
    ]
