# Generated by Django 6.0 on 2025-12-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='notenaddress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
